In [2]:
from keras.models import Model,Sequential
from keras.layers import Input, Dense,Dropout,Activation, Flatten,Convolution2D,MaxPooling2D
import numpy as np
from keras.utils import np_utils
from keras.datasets import imdb

In [3]:
(x_train, y_train),(x_test, y_test) = imdb.load_data(num_words = 10000)

In [4]:
x = np.concatenate((x_train,x_test), axis = 0)
y = np.concatenate((y_train,y_test), axis = 0)

In [5]:
print("Categories:", np.unique(y))
print("Number of unique words:", len(np.unique(np.hstack(x))))

Categories: [0 1]
Number of unique words: 9998


In [6]:
index = imdb.get_word_index()
reverse_index = dict([(value, key) for (key, value) in index.items()]) 
decoded = " ".join( [reverse_index.get(i - 3, "#") for i in x[0]] )
print(decoded)

# this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert # is an amazing actor and now the same being director # father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for # and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also # to the two little boy's that played the # of norman and paul they were just brilliant children are often left out of the # list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you thi

In [7]:
x[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

In [8]:
def vectorize(sequences, dimension = 10000):
    results = np.zeros((len(sequences), dimension))
    print(results.shape)
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1
    return results

In [9]:
x = vectorize(x)

(50000, 10000)


In [10]:
x

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [11]:
y = np.array(y).astype("float32")

In [12]:
x_train = x[:40000]
x_test = x[40000:]
y_train = y[:40000]
y_test = y[40000:]

In [13]:
x_train

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [14]:
y_train

array([1., 0., 0., ..., 1., 0., 1.], dtype=float32)

In [15]:
model = Sequential()
model.add(Dense(50,activation="relu",input_shape = (10000,)))
model.add(Dropout(0.3, noise_shape=None,seed=None))
model.add(Dense(50,activation="relu"))
model.add(Dropout(0.2, noise_shape=None,seed=None))
model.add(Dense(50,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

In [16]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [17]:
model.fit(x_train,y_train,batch_size=32,epochs=10,verbose=1)

Epoch 1/10
1250/1250 [==============================] - 13s 8ms/step - loss: 0.3195 - accuracy: 0.8643
Epoch 2/10
1250/1250 [==============================] - 11s 8ms/step - loss: 0.2032 - accuracy: 0.9211
Epoch 3/10
1250/1250 [==============================] - 12s 9ms/step - loss: 0.1447 - accuracy: 0.9478
Epoch 4/10
1250/1250 [==============================] - 9s 7ms/step - loss: 0.1007 - accuracy: 0.9630
Epoch 5/10
1250/1250 [==============================] - 8s 6ms/step - loss: 0.0767 - accuracy: 0.9712
Epoch 6/10
1250/1250 [==============================] - 11s 9ms/step - loss: 0.0624 - accuracy: 0.9765
Epoch 7/10
1250/1250 [==============================] - 9s 8ms/step - loss: 0.0557 - accuracy: 0.9792
Epoch 8/10
1250/1250 [==============================] - 8s 7ms/step - loss: 0.0467 - accuracy: 0.9816
Epoch 9/10
1250/1250 [==============================] - 8s 7ms/step - loss: 0.0459 - accuracy: 0.9826
Epoch 10/10
1250/1250 [==============================] - 13s 11ms/step - loss:

In [18]:
score=model.evaluate(x_test,y_test,verbose=0) 

In [19]:
score

[0.5558310151100159, 0.8840000033378601]

In [20]:
x_train.shape

(40000, 10000)